/** Sample paste, used by the "Load example" button and by the tests. */
export const EXAMPLE_DIFF = `-<!-- wp:group {"metadata":{"name":"Featured stories in region"},"align":"wide","style":{"border":{"radius":{"topLeft":"50px","topRight":"50px","bottomLeft":"50px","bottomRight":"50px"}},"elements":{"link":{"color":{"text":"var:preset|color|white"}}},"spacing":{"padding":{"top":"var:preset|spacing|md-56","bottom":"var:preset|spacing|lg-96","left":"var:preset|spacing|md-56","right":"var:preset|spacing|md-56"},"blockGap":"var:preset|spacing|md-40"}},"backgroundColor":"primary-text","textColor":"white","layout":{"type":"default"}} -->
-<div class="wp-block-group alignwide has-white-color has-primary-text-background-color has-text-color has-background has-link-color" style="border-top-left-radius:50px;border-top-right-radius:50px;border-bottom-left-radius:50px;border-bottom-right-radius:50px;padding-top:var(--wp--preset--spacing--md-56);padding-right:var(--wp--preset--spacing--md-56);padding-bottom:var(--wp--preset--spacing--lg-96);padding-left:var(--wp--preset--spacing--md-56)"><!-- wp:heading {"className":"is-style-h4"} -->
+<!-- wp:group {"metadata":{"name":"Featured stories wrap"},"align":"full","layout":{"type":"constrained","contentSize":"1270px"}} -->
+<div class="wp-block-group alignfull"><!-- wp:group {"metadata":{"name":"Featured stories in region"},"style":{"border":{"radius":{"topLeft":"50px","topRight":"50px","bottomLeft":"50px","bottomRight":"50px"}},"elements":{"link":{"color":{"text":"var:preset|color|white"}}},"spacing":{"padding":{"top":"var:preset|spacing|md-56","bottom":"var:preset|spacing|lg-96","left":"var:preset|spacing|md-56","right":"var:preset|spacing|md-56"},"blockGap":"var:preset|spacing|md-40"}},"backgroundColor":"primary-text","textColor":"white","layout":{"type":"default"}} -->
+<div class="wp-block-group has-white-color has-primary-text-background-color has-text-color has-background has-link-color" style="border-top-left-radius:50px;border-top-right-radius:50px;border-bottom-left-radius:50px;border-bottom-right-radius:50px;padding-top:var(--wp--preset--spacing--md-56);padding-right:var(--wp--preset--spacing--md-56);padding-bottom:var(--wp--preset--spacing--lg-96);padding-left:var(--wp--preset--spacing--md-56)"><!-- wp:heading {"className":"is-style-h4"} -->
 <h2 class="wp-block-heading is-style-h4">Featured stories</h2>
 <!-- /wp:heading --></div>
 <!-- /wp:group -->`;
